class MyException :Exception()
{
    fun error()
    {
        println("Error called")
    }

}